### PR TITLE
AUR-32 adding development version of the application

### PR DESCRIPTION
**Pull request by QuantamHD**

### CODE REVIEW

**Comment by Flaque** [comment]
Build is failing O.O 
Something probably went wrong with your lock file? I'm gonna take a look at it.

**Comment by QuantamHD** [comment]
Yeah, its the electron dep

**Comment by Flaque** [comment]
Okay, I did some pruning of the package.json and hopefully fixed it? We'll see.

**Comment by Flaque** [comment]
Cool, build works but linter fails. Go run `npm run lint` on your project, or just install visual studio's [eslint plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and then follow that.

**Comment by Flaque** [comment]
https://travis-ci.org/tundra-code/aurora/builds/279333552#L3053

**Comment by QuantamHD** [comment]
Okay fixed.

**Comment by Flaque** [comment]
Ship it :P 
doggo-gif

P.S. When you make changes to your PR, you don't need to squash as long as when you're done, you choose the `Squash and merge` option in that big green button.

**Comment by QuantamHD** [comment]
I prefer to control the history myself.

**Pull request merged**
